import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f4",
        surface: "#fcf9f4",
        "surface-container-low": "#f6f3ee",
        "surface-container": "#f0ede8",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        primary: "#405873",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#b0c9e9",
        secondary: "#8f4c35",
        "secondary-container": "#ffa98c",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59d",
        tertiary: "#425c38",
        "tertiary-fixed": "#cdecbd",
        "tertiary-fixed-dim": "#b1cfa2",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#43474d",
        outline: "#74777e",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001d36",
        "on-primary-fixed-variant": "#304864",
        "on-secondary-container": "#793b25",
        "on-tertiary-container": "#dbfacb",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f4",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        "surface-tint": "#48607c",
        "surface-dim": "#dcdad5",
        "surface-variant": "#e5e2dd",
        "outline-variant": "#c3c6ce",
        "on-secondary-fixed": "#390c00",
        "on-secondary-fixed-variant": "#723520",
        "on-tertiary-fixed": "#092104",
        "on-tertiary-fixed-variant": "#344d2b",
        "primary-container": "#58708d",
        "tertiary-container": "#5a754f",
        "inverse-primary": "#b0c9e9",
        "error-container": "#ffdad6",
        "on-background": "#1c1c19",
        "on-primary-container": "#ebf2ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Plus Jakarta Sans"],
        label: ["Plus Jakarta Sans"],
      },
      boxShadow: {
        "clay-card": "0 10px 30px rgba(31, 36, 48, 0.05)",
        "clay-inset": "inset 2px 2px 5px rgba(31, 36, 48, 0.03), inset -2px -2px 5px rgba(255, 255, 255, 0.7)",
        "clay-raised": "10px 10px 20px rgba(31,36,48,0.03), -10px -10px 20px rgba(255,255,255,0.8)",
      },
    },
  },
  plugins: [],
};
export default config;
